# SIAU Service
SIAU_SERVICE_URL=${SIAU_SERVICE_URL:-http://localhost:8088}
SIAU_PORT=${SIAU_PORT:-8088}
SPRING_R2DBC_URL=${SPRING_R2DBC_URL:-r2dbc:postgresql://localhost:5432/nexosalud}
SPRING_R2DBC_USERNAME=${SPRING_R2DBC_USERNAME:-postgres}
SPRING_R2DBC_PASSWORD=${SPRING_R2DBC_PASSWORD:-postgres}
